### ISSUE TITLE
while reading data from sqlite all the column names are coming in lower case in ionic app (IOS).

### ISSUE THREAD

**Issue by NeeteshSonkiya** [jepiqueau/react-sqlite-app-starter#1]
I am trying to execute select  query to read data from sqlite tables.  but while reading data all the column names are coming in lower case in ios but its coming pascal case in android.

query = select * from testtable;
this.sqlite.query(query, values);
----------------------------------------
query result- (ios)
id, firstname, lastname, address, mobilenumber
-------------------------------------------------------
query result- (android)
ID, FirstName, LastName, Address, MobileNumber
-----------------------------------------------------------
Please help me out to get same column name from sqlite table.
Thanks in advance

**Comment by jepiqueau** [comment]
@NeeteshSonkiya This is fixed since release 2.1.0
