### ISSUE TITLE
On page refresh the sqlite isn't called from app.tsx anymore

### ISSUE THREAD

**Issue by stealthAngel** [jepiqueau/react-sqlite-app-starter#10]
I tried to reproduce this error on a clean project in the simplest way I can explain
I updated only tab3.tsx with the code above. Nothing more than a query that shows some names on the page.

```
import React, { useEffect, useState } from 'react';
import { IonContent, IonHeader, IonPage, IonText, IonTitle, IonToolbar } from '@ionic/react';
import ExploreContainer from '../components/ExploreContainer';
import './Tab3.css';
import { SQLiteDBConnection } from '@capacitor-community/sqlite';
import { sqlite } from '../App';

const Tab3: React.FC = () => {
  const [tests, setTests] = useState<any>([]);
  useEffect(() => {
    const initialize = async (): Promise<Boolean> => {
      try {
        let db: SQLiteDBConnection = await sqlite.createConnection("db_issue9");
        await db.open();
        let randomText = (Math.random() + 1).toString(36).substring(7);
        await db.run("INSERT INTO test (name) VALUES (?)", [randomText]);
        let res: any = await db.query("SELECT * FROM test");
        setTests(res.values);
        console.log(`query ${res}`);
        await db.close();
        return true;
      }
      catch (err) {
        console.log(`Error: ${err}`);
        return false;
      }
    }
    initialize();
  }, []);
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 3</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 3</IonTitle>
          </IonToolbar>
        </IonHeader>
        {/* <ExploreContainer name="Tab 3 page" /> */}
        <div className="container">
          {tests.map((x: any, index: any) =>
            <div key={index}><IonText>
              {index} {x.name}
            </IonText>
            </div>
          )}
        </div>
      </IonContent>
    </IonPage>
  );
};

export default Tab3;
```

This code only if your first-page load is tab1.tsx.
If you refresh the page while you are on tab3.tsx it won't work.
I couldn't figure out a way to fix this problem.

https://user-images.githubusercontent.com/23656202/136422163-828c8c44-624d-42c1-bc1f-e6d209eb8cfb.mp4

**Comment by stealthAngel** [comment]
Hey @jepiqueau ,

Thanks for your reply.
The error still occurs. You could try using a different browser. e.g internet explorer firefox maxthon etc.

The only thing I did was changing tab3.tsx to the code above.

Then to run the project I did, 
```
npm install
ionic serve
```

Refreshing the page  on `localhost:8100/tab3` gives that error.

**Comment by stealthAngel** [comment]
https://github.com/stealthAngel/react-sqlite-app-starter/tree/test3

The issue still occurs. I made a fork branch with the problem.

**Comment by jepiqueau** [comment]
@stealthAngel Well i test it on Mac with Google and Safari and on Windows 10 Edge, Google, Firefox and i cannot reproduce the error . I clone the app and copy the code from above for the Tab3. So i really do not know what to do more

**Comment by stealthAngel** [comment]
@jepiqueau I did exactly that, still the same problem

![image](https://user-images.githubusercontent.com/23656202/136573135-cf0c1450-733e-4fd3-8f0d-4d9d589a9b86.png)
![image](https://user-images.githubusercontent.com/23656202/136573587-f3eda795-dc2a-40c8-a4b5-fd639b543c94.png)
![image](https://user-images.githubusercontent.com/23656202/136573646-36b410fe-15e9-4761-818d-00e0a35933a4.png)
![image](https://user-images.githubusercontent.com/23656202/136573741-7146560e-3bee-40df-a2dc-7d8cba27098a.png)


It seems for me it only works on firefox.

**Comment by stealthAngel** [comment]
Yes, you got it. It's the page refresh on tab3 that reproduces the error.

**Comment by stealthAngel** [comment]
So the load has to be completed first that makes sense. I don't currently know how to do that. Maybe await useEffect app.tsx

**Comment by jepiqueau** [comment]
@stealthAngel i don't no myself too. In Vue we move this in the main.ts file. Here i tried to move it in the index.ts  file but we cannot define useSQLite in the index.ts

**Comment by stealthAngel** [comment]
Hey thanks for your reply, 
![image](https://user-images.githubusercontent.com/23656202/136832660-47e09a55-c2c9-429b-ac01-783e71830382.png)

I can't find those files.
