### ISSUE TITLE
shall I close() the database connection everytime?

### ISSUE THREAD

**Issue by blatoo** [jepiqueau/react-sqlite-app-starter#13]
Hi all,

thanks very much for this great plugin, I am just new to sql world.

I just find a strange problem, every time after insert data with "run("...", [...])", I have to close() the connection, otherwise the data won't be saved into the table. Is it true?

Shall I close() database every time after I changed some data in a table?

Conny

**Comment by jepiqueau** [comment]
@blatoo are you using the Web part of the plugin?. If yes the database is in-memory so you do not need to close the connections after each sql statement. there is a saveToStore method which allows the database to be saved on store (indexedDB) at your convenience. For native iOS, Android or desktop Électron you do not need to worry about this

**Comment by blatoo** [comment]
Hi Jepiqueau, 

thanks!  Ah, the "saveToStore" is at the top of the doc, I just ignored it... :D 

Merry chrismas and have a nice holiday season! 
Conny
