### ISSUE TITLE
Is it possible in Json file also "create table if not exists ..."?

### ISSUE THREAD

**Issue by blatoo** [jepiqueau/react-sqlite-app-starter#14]
Hi all,

I just read the json file, I found out that, the json file will insert table and every every time. Is it possible that also let json file import to insert table and data like "CREATE TABLE IF NOT EXISTS test (...)" ???

thanks for the great plugin and the great template!

Best,
Conny

**Comment by jepiqueau** [comment]
@blatoo this is done by the plugin itself.the sol statement to create the table in importFromJson includes the IF NOT EXIST so you do not née to worry about this. Home this clarify. Thanks for using the plugin

**Comment by blatoo** [comment]
Wow, thats great!!! Thanks!!! 👯
