### ISSUE TITLE
expected magic word 00 61 73 6d, found 3c 21 44 4f @+0) #6

### ISSUE THREAD

**Issue by jkrrish-ac** [jepiqueau/react-sqlite-app-starter#16]
I was trying to integrate jeep-sqlite to my react app. I am getting the following error when running

Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import * as serviceWorkerRegistration from './serviceWorkerRegistration';
import reportWebVitals from './reportWebVitals';
import { Provider } from 'react-redux';
import { store } from './store';
import { HTMLAttributes } from 'react';

import { defineCustomElements as jeepSqlite, applyPolyfills, JSX as LocalJSX } from "jeep-sqlite/loader";
import { Capacitor } from '@capacitor/core';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';

type StencilToReact = {
[P in keyof T]?: T[P] & Omit<HTMLAttributes, 'className'> & {
class?: string;
};
} ;

declare global {
export namespace JSX {
interface IntrinsicElements extends StencilToReact<LocalJSX.IntrinsicElements> {
}
}
}

applyPolyfills().then(() => {
jeepSqlite(window);
});

window.addEventListener('DOMContentLoaded', async () => {
const platform = Capacitor.getPlatform();
const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
try {
if (platform === "web") {
const jeepEl = document.createElement("jeep-sqlite");
document.body.appendChild(jeepEl);
await customElements.whenDefined('jeep-sqlite');
await sqlite.initWebStore();
}
const ret = await sqlite.checkConnectionsConsistency();
const isConn = (await sqlite.isConnection("db_employee")).result;
var db: SQLiteDBConnection
if (ret.result && isConn) {
db = await sqlite.retrieveConnection("db_employee");
} else {
db = await sqlite.createConnection("db_employee", false, "no-encryption", 1);
}

await db.open();
let query = `
CREATE TABLE IF NOT EXISTS stream (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL
);
`

const res: any = await db.execute(query);
console.log(`res: ${JSON.stringify(res)}`);
await db.close();
await sqlite.closeConnection("db_employee");

ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorkerRegistration.unregister();
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
} catch (err) {
console.log(Error: ${err});
throw new Error(Error: ${err})
}

});

**Comment by jepiqueau** [comment]
@mckodea  delete the sql-wasm.wasm file from the public/assets folder and copy the one from node-modules/sql.js/dist/sql-wasm.wasm on the public/assets folder. This will remove the error

**Comment by jaimeburnap** [comment]
This worked for me too. Not sure why it needs to be done.

**Comment by jepiqueau** [comment]
@jaimeburnap it is required each time the sql.js release change.

**Comment by hhimanshu** [comment]
I added the following script in `package.json`

```json
"copysqlwasm": "cp node_modules/sql.js/dist/sql-wasm.wasm public/assets"
```

Then ran
```sh
npm run copysqlwasm
```

After that, when I restarted the app using `npm start`, I was able to see the data in browser as well.
