### ISSUE TITLE
react-sqlite-hook can only support sqlite 3.3.3-1, please update

### ISSUE THREAD

**Issue by blatoo** [jepiqueau/react-sqlite-app-starter#18]
Hi Jepiqueau,

The installation of `react-sqlite-hook` has a little problem with `@capacitor-community/sqlite`, because it is only support to `3.3.3-1`, but current version is already 3.4.1-1..., can you update the `react-sqlite-hook`?

**Comment by jepiqueau** [comment]
@blatoo you right i have to update it. Thanks for remind me this

**Comment by jepiqueau** [comment]
@blatoo this is done
