### ISSUE TITLE
Compound primary Key when ImportFromJSON

### ISSUE THREAD

**Issue by alu0100991659** [jepiqueau/react-sqlite-app-starter#7]
Hi, is it possible to define a compound primary key when creating a database from a JSON?

The example bellow  didn't work

export const dataToImport = {
    "database": "db",
    "version": 1,
    "encrypted": false,
    "mode": "full",
    "tables": [
        {
            "name": "table1",
            "schema": [
                {
                    "column": "id",
                    "value": "INTEGER PRIMARY KEY NOT NULL"
                },
                {
                    "column": "id2",
                    "value": "INTEGER PRIMARY KEY NOT NULL"
                }
            ],
            "indexes": [],
            "values": [
                [
                    6,4
                ],
                [
                    6,5              
                ]
            ]
        }
   ]
}

**Comment by jepiqueau** [comment]
@alu0100991659 This has been fixed
