### ISSUE TITLE
App Database Buttons are working, but no database is beeing created

### ISSUE THREAD

**Issue by nsauter** [jepiqueau/react-sqlite-app-starter#8]
I cloned the repo, build the android assets and then compiled the app via android studio and ran it on my physical device. In TAB 2 all database check buttons are telling me, that everything is working just fine, but i cant see a database via the database inspector in android studio, or in my physical devices datamanager. Where is the generated database located?

**Comment by jepiqueau** [comment]
@nsauter This was already answered, the databases are created but you cannot see them via the database inspector in android studio. Go to the device explorer and look at your application and you will find the databases. You can save as the files to a folder in your PC or Mac and use DBBrowser to open them Hope this help

**Comment by nsauter** [comment]
I tried it with this react-sqlite-app-starter but cannot find it in the device explorer. Could you please tell me where it is located to check this? There is nothing beeing created imho.

**Comment by jepiqueau** [comment]
@nsauter Look at the manifest file if you clone it straight forward it should be `com.example.app.capacitor`

**Comment by jepiqueau** [comment]
@nsuter Did you find them if yes can you close the issue. Thanks for using the plugin

**Comment by nsauter** [comment]
Yeah, i found it. But it seems, thats its only visible with Android Studios Data Inspector. But nevermind. Im going to Close this issue now
